-- Persistent abuse protection for canonical FarmConnect business tables.
-- This migration does not change money, ownership, KYC decisions, or existing
-- business rows. It records authenticated mutation attempts and rejects only
-- attempts above a deliberately generous per-workflow threshold.

begin;

create table if not exists public.farmconnect_rate_limit_events (
  id bigint generated by default as identity primary key,
  actor_auth_user_id uuid not null,
  workflow text not null,
  operation text not null,
  occurred_at timestamptz not null default now()
);

create index if not exists farmconnect_rate_limit_events_lookup_idx
  on public.farmconnect_rate_limit_events(actor_auth_user_id, workflow, operation, occurred_at desc);

alter table public.farmconnect_rate_limit_events enable row level security;
revoke all on table public.farmconnect_rate_limit_events from public, anon, authenticated;
grant select, insert, delete on table public.farmconnect_rate_limit_events to service_role;

create or replace function public.farmconnect_enforce_rate_limit(
  p_workflow text,
  p_operation text,
  p_max_attempts integer,
  p_window_seconds integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_count integer;
  v_effective_max integer;
  v_workflow text := lower(trim(coalesce(p_workflow, '')));
  v_operation text := lower(trim(coalesce(p_operation, 'mutation')));
begin
  -- Trusted service jobs have no end-user Auth UID and remain outside this
  -- customer/Admin abuse boundary. Anonymous callers are rejected elsewhere by
  -- the canonical RPC grants and RLS policies.
  if v_actor is null then
    return;
  end if;
  if v_workflow = '' or p_max_attempts < 1 or p_window_seconds < 1 then
    raise exception 'RATE_LIMIT_CONFIGURATION_INVALID';
  end if;

  -- Admin review queues legitimately process more records than one customer.
  -- The guard remains active but uses a 10x operational ceiling for active Admins.
  v_effective_max := case when public.is_admin() then p_max_attempts * 10 else p_max_attempts end;

  -- Serialize concurrent attempts for the same actor and workflow so parallel
  -- double-clicks cannot race past the counter.
  perform pg_advisory_xact_lock(hashtextextended(v_actor::text || '|' || v_workflow || '|' || v_operation, 0));

  -- Bound storage growth without deleting another actor's recent evidence.
  delete from public.farmconnect_rate_limit_events
  where actor_auth_user_id = v_actor
    and occurred_at < now() - interval '7 days';

  select count(*)::integer
  into v_count
  from public.farmconnect_rate_limit_events event
  where event.actor_auth_user_id = v_actor
    and event.workflow = v_workflow
    and event.operation = v_operation
    and event.occurred_at >= now() - make_interval(secs => p_window_seconds);

  if v_count >= v_effective_max then
    raise exception 'FARMCONNECT_RATE_LIMITED:%', upper(v_workflow)
      using errcode = 'P0001', hint = 'Wait before retrying. Do not repeatedly submit the same request.';
  end if;

  insert into public.farmconnect_rate_limit_events(actor_auth_user_id, workflow, operation)
  values (v_actor, v_workflow, v_operation);
end;
$$;

revoke all on function public.farmconnect_enforce_rate_limit(text,text,integer,integer) from public, anon, authenticated;
grant execute on function public.farmconnect_enforce_rate_limit(text,text,integer,integer) to service_role;

create or replace function public.farmconnect_business_rate_limit_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.farmconnect_enforce_rate_limit(TG_ARGV[0], lower(TG_OP), TG_ARGV[1]::integer, TG_ARGV[2]::integer);
  return case when TG_OP = 'DELETE' then old else new end;
end;
$$;

revoke all on function public.farmconnect_business_rate_limit_trigger() from public, anon, authenticated;

do $$
declare
  item record;
begin
  for item in
    select * from (values
      ('manual_payment_requests', 'payment', 30, 3600),
      ('caretaker_applications', 'caretaker_application', 5, 3600),
      ('farm_care_requests', 'care_request', 30, 3600),
      ('withdrawal_requests', 'withdrawal', 10, 3600),
      ('rooster_sale_requests', 'rooster_sale', 20, 3600),
      ('rooster_care_plans', 'care_plan', 10, 3600),
      ('customer_kyc_profiles', 'customer_kyc', 10, 3600)
    ) as configured(table_name, workflow, max_attempts, window_seconds)
  loop
    if to_regclass('public.' || item.table_name) is not null then
      execute format('drop trigger if exists %I on public.%I', 'trg_rate_limit_' || item.table_name, item.table_name);
      execute format(
        'create trigger %I before insert or update on public.%I for each row execute function public.farmconnect_business_rate_limit_trigger(%L,%L,%L)',
        'trg_rate_limit_' || item.table_name,
        item.table_name,
        item.workflow,
        item.max_attempts,
        item.window_seconds
      );
    end if;
  end loop;
end;
$$;

create or replace function public.farmconnect_rate_limit_version()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'migration', '078_persistent_business_rate_limit',
    'event_table', to_regclass('public.farmconnect_rate_limit_events') is not null,
    'guard_function', to_regprocedure('public.farmconnect_enforce_rate_limit(text,text,integer,integer)') is not null,
    'trigger_function', to_regprocedure('public.farmconnect_business_rate_limit_trigger()') is not null,
    'business_trigger_count', (
      select count(*) from pg_trigger
      where not tgisinternal and tgname like 'trg_rate_limit_%'
    )
  );
$$;

revoke all on function public.farmconnect_rate_limit_version() from public, anon, authenticated;
grant execute on function public.farmconnect_rate_limit_version() to service_role;

commit;

select public.farmconnect_rate_limit_version() as verification;
