-- Durable heartbeat for every authorized KaFarm Guardian monitor invocation.
-- This is operational evidence only and never mutates a FarmConnect workflow.

begin;

create table if not exists public.kafarm_guardian_monitor_runs (
  id bigint generated by default as identity primary key,
  ran_at timestamptz not null default now(),
  deployment_commit text null,
  finding_count integer not null default 0 check (finding_count >= 0),
  persisted_incident_count integer not null default 0 check (persisted_incident_count >= 0),
  snapshot_ok boolean not null,
  persistence_ok boolean not null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists kafarm_guardian_monitor_runs_ran_at_idx
  on public.kafarm_guardian_monitor_runs(ran_at desc);

alter table public.kafarm_guardian_monitor_runs enable row level security;
revoke all on table public.kafarm_guardian_monitor_runs from public, anon, authenticated;
grant select, insert on table public.kafarm_guardian_monitor_runs to service_role;

create or replace function public.kafarm_guardian_monitor_health()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'migration', '079_kafarm_monitor_run_ledger',
    'run_table', to_regclass('public.kafarm_guardian_monitor_runs') is not null,
    'latest_run_at', (select max(ran_at) from public.kafarm_guardian_monitor_runs),
    'runs_last_48_hours', (select count(*) from public.kafarm_guardian_monitor_runs where ran_at >= now() - interval '48 hours'),
    'latest_run_ok', coalesce((select snapshot_ok and persistence_ok from public.kafarm_guardian_monitor_runs order by ran_at desc limit 1), false)
  );
$$;

revoke all on function public.kafarm_guardian_monitor_health() from public, anon, authenticated;
grant execute on function public.kafarm_guardian_monitor_health() to service_role;

commit;

select public.kafarm_guardian_monitor_health() as verification;
