import Link from "next/link";

export default function CaretakerCareersPage() {
  const responsibilities = ["Follow assigned daily procedures", "Record feed, weight, and health", "Upload clear work evidence", "Report concerns honestly and promptly"];
  return <main className="min-h-screen bg-[#f5f1e5] text-[#173d2e]">
    <header className="border-b border-white/20 bg-[#075f48] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link href="/" className="flex items-center gap-3 font-black"><img src="/farmconnect/home/farmconnect-brand-mark.png" alt="" className="h-11 w-11 rounded-2xl bg-white" />FarmConnect Caretakers</Link><Link href="/login" className="rounded-xl border border-white/40 px-4 py-2 text-sm font-black">Sign In</Link></div></header>
    <section className="relative isolate overflow-hidden bg-[#064d3b] text-white"><div className="absolute inset-0 -z-20 bg-[url('/farmconnect/farmconnect-hero-wallpaper.jpg')] bg-cover bg-center" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(3,48,36,.97),rgba(3,48,36,.78),rgba(3,48,36,.38))]" /><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><p className="text-xs font-black uppercase tracking-[.16em] text-[#ffe37a]">Work with FarmConnect</p><h1 className="mt-4 max-w-4xl text-5xl font-black leading-[.95] tracking-[-.04em] sm:text-7xl">Help care for roosters. Build a trusted record of your work.</h1><p className="mt-6 max-w-2xl text-lg font-bold leading-8 text-emerald-50">Receive assigned farm tasks, follow clear procedures, document your work, and help customers stay connected to their rooster.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/apply-caretaker" className="rounded-2xl bg-[#ffd84a] px-6 py-4 font-black text-[#173d2e]">Apply as Caretaker</Link><Link href="/login" className="rounded-2xl border border-white/40 bg-white/10 px-6 py-4 font-black">Caretaker Sign In</Link></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-8 px-5 py-16 sm:px-8 lg:grid-cols-2"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#16704f]">The work</p><h2 className="mt-3 text-4xl font-black">Care that customers can understand and trust.</h2><div className="mt-7 grid gap-3">{responsibilities.map((item,index)=><div key={item} className="flex items-center gap-4 rounded-2xl bg-white p-4 shadow-sm"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-emerald-100 font-black text-emerald-800">{index+1}</span><b>{item}</b></div>)}</div></div><div className="rounded-[30px] bg-white p-7 shadow-xl"><p className="text-xs font-black uppercase text-[#16704f]">How application works</p>{["Complete your application and documents", "Admin verifies your identity and experience", "Approved account receives Caretaker access", "Admin assigns tasks based on farm needs", "Submit evidence for review and customer Care Logs"].map((item,index)=><div key={item} className="mt-5 flex gap-4"><span className="font-black text-[#16704f]">0{index+1}</span><p className="font-bold">{item}</p></div>)}<Link href="/apply-caretaker" className="mt-8 block rounded-2xl bg-[#0a7654] px-6 py-4 text-center font-black text-white">Start Your Application</Link></div></section>
    <footer className="bg-[#063f31] px-5 py-8 text-white"><div className="mx-auto flex max-w-7xl justify-between gap-4"><Link href="/" className="font-black">Customer Homepage</Link><Link href="/login" className="font-black">Sign In</Link></div></footer>
  </main>;
}
